app = "uncl"
primary_region = "ord"

[build]
  builder = "paketobuildpacks"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 100

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[checks]
  [checks.alive]
    type = "http"
    interval = "10s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
